/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/battery/assets/{serial}/compensation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compensation For Asset */
        get: operations["compensation_for_asset_battery_assets__serial__compensation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_catalog_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/models/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_catalog_models__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description Tạo đơn và khoá snapshot.
         *
         *     Sau lời gọi này, đơn không còn phụ thuộc vào bảng giá. Bảng giá đổi ngày
         *     mai không làm đổi con số trong đơn.
         */
        post: operations["create_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_orders__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/on-road": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** On Road Quote */
        get: operations["on_road_quote_pricing_on_road_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/running-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Running Cost */
        get: operations["running_cost_pricing_running_cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Promotions
         * @description Ưu đãi còn hiệu lực tại một mốc thời gian.
         *
         *     Mặc định là hôm nay, nhưng tra cứu lại một đơn cũ phải truyền đúng ngày của
         *     đơn — ưu đãi đã hết hạn vẫn phải giải thích được vì sao từng được áp.
         */
        get: operations["list_promotions_promotions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppliedPromotionOut */
        AppliedPromotionOut: {
            /** Code */
            code: string;
            /** Discount Vnd */
            discount_vnd: number;
            /** Name */
            name: string;
            /** Terms Url */
            terms_url: string | null;
        };
        /** ColorOut */
        ColorOut: {
            /** Code */
            code: string;
            /** Exterior */
            exterior: boolean;
            /** Name */
            name: string;
        };
        /**
         * CompensationOut
         * @description Số tiền đòi khách trả, nên trả kèm toàn bộ căn cứ đã dùng.
         */
        CompensationOut: {
            /** Compensation Vnd */
            compensation_vnd: number;
            /** Floor Applied */
            floor_applied: boolean;
            /**
             * List Price As Of
             * Format: date
             */
            list_price_as_of: string;
            /** List Price Vnd */
            list_price_vnd: number;
            /** Months Used */
            months_used: number;
            /** Warranty Months */
            warranty_months: number;
            /**
             * Warranty Policy As Of
             * Format: date
             */
            warranty_policy_as_of: string;
        };
        /** CreateOrderIn */
        CreateOrderIn: {
            /** As Of */
            as_of?: string | null;
            /** Code */
            code: string;
            /** Deposit Vnd */
            deposit_vnd: number;
            /** @default battery_included */
            ownership_model: components["schemas"]["OwnershipModel"];
            /** Province Code */
            province_code: string;
            /** Trim Id */
            trim_id: number;
        };
        /**
         * FuelType
         * @enum {string}
         */
        FuelType: "gasoline" | "diesel";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LineItemOut */
        LineItemOut: {
            /** Amount Vnd */
            amount_vnd: number;
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** ModelOut */
        ModelOut: {
            /** Category */
            category: string;
            /** Code */
            code: string;
            /** Colors */
            colors: components["schemas"]["ColorOut"][];
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Seats */
            seats: number | null;
            /** Segment */
            segment: string | null;
            /** Trims */
            trims: components["schemas"]["TrimOut"][];
        };
        /** OnRoadQuoteOut */
        OnRoadQuoteOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Discount Vnd */
            discount_vnd: number;
            /** Items */
            items: components["schemas"]["LineItemOut"][];
            /** Monthly Battery Fee Vnd */
            monthly_battery_fee_vnd: number | null;
            /** Ownership Model */
            ownership_model: string;
            /** Promotions */
            promotions: components["schemas"]["AppliedPromotionOut"][];
            /** Province Code */
            province_code: string;
            /** Total Vnd */
            total_vnd: number;
            /** Vehicle Price Vnd */
            vehicle_price_vnd: number;
        };
        /** OrderOut */
        OrderOut: {
            /** Channel */
            channel: string;
            /** Code */
            code: string;
            /** Deposit Vnd */
            deposit_vnd: number;
            /** Price Snapshot */
            price_snapshot: {
                [key: string]: unknown;
            };
            /** Province Code */
            province_code: string;
            /**
             * Quoted On
             * Format: date
             */
            quoted_on: string;
            /** Status */
            status: string;
            /** Total Vnd */
            total_vnd: number;
            /** Trim Id */
            trim_id: number;
        };
        /**
         * OwnershipModel
         * @description Hai mô hình sở hữu pin. Đây là hai biến thể giá, không phải một cờ.
         * @enum {string}
         */
        OwnershipModel: "battery_included" | "battery_lease";
        /** PromotionOut */
        PromotionOut: {
            /** Code */
            code: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Terms Url */
            terms_url: string | null;
        };
        /** RunningCostOut */
        RunningCostOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Electricity Price As Of
             * Format: date
             */
            electricity_price_as_of: string;
            /** Ev Monthly Cost Vnd */
            ev_monthly_cost_vnd: number;
            /**
             * Fuel Price As Of
             * Format: date
             */
            fuel_price_as_of: string;
            /** Ice Monthly Cost Vnd */
            ice_monthly_cost_vnd: number;
            /** Monthly Km */
            monthly_km: number;
            /** Monthly Saving Vnd */
            monthly_saving_vnd: number;
        };
        /**
         * SpecOut
         * @description Thông số có kiểu. `ai/` đọc đúng schema này, không đọc văn bản mô tả.
         */
        SpecOut: {
            /** Drivetrain */
            drivetrain?: string | null;
            /** Fast Charge Minutes */
            fast_charge_minutes?: number | null;
            /** Max Power W */
            max_power_w?: number | null;
            /** Max Torque Nm */
            max_torque_nm?: number | null;
            /** Motor Count */
            motor_count?: number | null;
            /** Range Nedc Km */
            range_nedc_km?: number | null;
            /** Range Per Charge Km */
            range_per_charge_km?: number | null;
            /** Top Speed Kmh */
            top_speed_kmh?: number | null;
        };
        /** TrimOut */
        TrimOut: {
            /** Code */
            code: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            spec?: components["schemas"]["SpecOut"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compensation_for_asset_battery_assets__serial__compensation_get: {
        parameters: {
            query: {
                incident_on: string;
            };
            header?: never;
            path: {
                serial: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompensationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_catalog_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
        };
    };
    get_model_catalog_models__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_orders__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    on_road_quote_pricing_on_road_get: {
        parameters: {
            query: {
                trim_id: number;
                province_code: string;
                ownership_model?: components["schemas"]["OwnershipModel"];
                /** @description Mốc thời gian tính giá. Bỏ trống thì lấy hôm nay; báo giá cho một đơn cũ phải truyền đúng ngày của đơn đó. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnRoadQuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    running_cost_pricing_running_cost_get: {
        parameters: {
            query: {
                monthly_km: number;
                ev_consumption_kwh_per_100km_x10: number;
                ice_consumption_litres_per_100km_x10: number;
                fuel_type?: components["schemas"]["FuelType"];
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunningCostOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_promotions_promotions_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
