"""khoi tao lich su bang

Revision ID: 63e4b2cef3fc
Revises:
Create Date: 2026-09-14 13:08:04.908538
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "63e4b2cef3fc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "battery_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serial", sa.String(length=64), nullable=False),
        sa.Column("trim_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("LEASED", "RETURNED", "LOST", "DAMAGED_BEYOND_REPAIR", name="batterystatus"),
            nullable=False,
        ),
        sa.Column("formed_on", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial"),
    )
    op.create_table(
        "battery_list_price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trim_id", sa.Integer(), nullable=True),
        sa.Column("price_vnd", sa.BigInteger(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "battery_warranty_policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("warranty_months", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_vehicle_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("category", sa.Enum("CAR", "MOTORBIKE", name="productcategory"), nullable=False),
        sa.Column("segment", sa.String(length=64), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "orders_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column(
            "channel", sa.Enum("DEPOSIT", "DIRECT_PURCHASE", name="orderchannel"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "DEPOSIT_PENDING",
                "DEPOSIT_PAID",
                "CONTRACT_SIGNED",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("trim_id", sa.Integer(), nullable=False),
        sa.Column("province_code", sa.String(length=16), nullable=False),
        sa.Column("quoted_on", sa.Date(), nullable=False),
        sa.Column("price_snapshot", sa.JSON(), nullable=False),
        sa.Column("total_vnd", sa.BigInteger(), nullable=False),
        sa.Column("deposit_vnd", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "pricing_electricity_price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region_code", sa.String(length=16), nullable=False),
        sa.Column("price_per_kwh_vnd", sa.BigInteger(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pricing_fuel_price",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fuel_type", sa.Enum("GASOLINE", "DIESEL", name="fueltype"), nullable=False),
        sa.Column("region_code", sa.String(length=16), nullable=False),
        sa.Column("price_per_litre_vnd", sa.BigInteger(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pricing_registration_fee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("province_code", sa.String(length=16), nullable=False),
        sa.Column("registration_tax_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("plate_fee_vnd", sa.BigInteger(), nullable=False),
        sa.Column("inspection_fee_vnd", sa.BigInteger(), nullable=False),
        sa.Column("road_fee_year_vnd", sa.BigInteger(), nullable=False),
        sa.Column("civil_insurance_year_vnd", sa.BigInteger(), nullable=False),
        sa.Column("service_fee_vnd", sa.BigInteger(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promotions_promotion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("terms_url", sa.String(length=512), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("FIXED_AMOUNT", "PERCENT_OF_PRICE", "BENEFIT_IN_KIND", name="promotionkind"),
            nullable=False,
        ),
        sa.Column("amount_vnd", sa.BigInteger(), nullable=True),
        sa.Column("percent", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("trim_id", sa.Integer(), nullable=True),
        sa.Column("province_code", sa.String(length=16), nullable=True),
        sa.Column("ownership_model", sa.String(length=32), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("stackable", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "catalog_color",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("exterior", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["catalog_vehicle_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id", "code", "exterior"),
    )
    op.create_table(
        "catalog_trim",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["catalog_vehicle_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id", "code"),
    )
    op.create_table(
        "catalog_spec",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trim_id", sa.Integer(), nullable=False),
        sa.Column("motor_count", sa.Integer(), nullable=True),
        sa.Column("max_power_w", sa.Integer(), nullable=True),
        sa.Column("max_torque_nm", sa.Integer(), nullable=True),
        sa.Column("range_nedc_km", sa.Integer(), nullable=True),
        sa.Column("range_per_charge_km", sa.Integer(), nullable=True),
        sa.Column("fast_charge_minutes", sa.Integer(), nullable=True),
        sa.Column("top_speed_kmh", sa.Integer(), nullable=True),
        sa.Column("drivetrain", sa.String(length=32), nullable=True),
        sa.Column("battery_capacity_kwh_x10", sa.Integer(), nullable=True),
        sa.Column("consumption_kwh_per_100km_x10", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trim_id"],
            ["catalog_trim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trim_id"),
    )
    op.create_table(
        "pricing_price_book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trim_id", sa.Integer(), nullable=False),
        sa.Column(
            "ownership_model",
            sa.Enum("BATTERY_INCLUDED", "BATTERY_LEASE", name="ownershipmodel"),
            nullable=False,
        ),
        sa.Column("list_price_vnd", sa.BigInteger(), nullable=False),
        sa.Column("monthly_battery_fee_vnd", sa.BigInteger(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trim_id"],
            ["catalog_trim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pricing_price_book")
    op.drop_table("catalog_spec")
    op.drop_table("catalog_trim")
    op.drop_table("catalog_color")
    op.drop_table("promotions_promotion")
    op.drop_table("pricing_registration_fee")
    op.drop_table("pricing_fuel_price")
    op.drop_table("pricing_electricity_price")
    op.drop_table("orders_order")
    op.drop_table("catalog_vehicle_model")
    op.drop_table("battery_warranty_policy")
    op.drop_table("battery_list_price")
    op.drop_table("battery_asset")
    # ### end Alembic commands ###
